#!/usr/bin/env node
/**
 * WollyCMS CLI — Run common operations from the command line.
 *
 * Usage:
 *   npx wolly migrate     Run pending database migrations
 *   npx wolly seed        Populate database with sample data
 *   npx wolly start       Start the production server
 *   npx wolly dev         Start development server with hot reload
 *   npx wolly export      Export all data as JSON to stdout
 *   npx wolly import <f>  Import data from a JSON file
 *   npx wolly health      Check server health
 */

const command = process.argv[2];

async function main() {
  switch (command) {
    case 'migrate': {
      const { migrate } = await import('drizzle-orm/better-sqlite3/migrator');
      const { getDb } = await import('./db/index.js');
      const { env } = await import('./env.js');
      const { mkdirSync } = await import('fs');
      const { dirname } = await import('path');

      const dbPath = env.DATABASE_URL.replace('sqlite:', '');
      mkdirSync(dirname(dbPath), { recursive: true });
      const db = getDb();
      console.log('Running migrations...');
      migrate(db, { migrationsFolder: './drizzle' });
      console.log('Migrations complete.');
      break;
    }

    case 'seed': {
      // Dynamically import the seed script
      await import('./db/seed.js');
      break;
    }

    case 'start': {
      await import('./index.js');
      break;
    }

    case 'export': {
      const { getDb } = await import('./db/index.js');
      const { sql } = await import('drizzle-orm');
      const db = getDb();

      const tables = [
        'content_types', 'block_types', 'pages', 'blocks', 'page_blocks',
        'menus', 'menu_items', 'taxonomies', 'terms', 'content_terms',
        'redirects', 'users', 'media', 'webhooks', 'api_keys',
      ];
      const data: Record<string, unknown[]> = {};
      for (const table of tables) {
        try {
          data[table] = db.all(sql.raw(`SELECT * FROM ${table}`));
        } catch {
          data[table] = [];
        }
      }
      console.log(JSON.stringify(data, null, 2));
      break;
    }

    case 'types': {
      const subcommand = process.argv[3];
      if (subcommand !== 'generate') {
        console.log('Usage: wolly types generate [--output <path>]');
        process.exit(1);
      }

      const outputIdx = process.argv.indexOf('--output');
      const outputPath = outputIdx > -1 ? process.argv[outputIdx + 1] : './wolly-types.d.ts';

      const { getDb } = await import('./db/index.js');
      const schema = await import('./db/schema/index.js');
      const { writeFileSync } = await import('fs');
      const db = getDb();

      const ctRows = await db.select().from(schema.contentTypes);
      const btRows = await db.select().from(schema.blockTypes);

      function fieldToTs(field: { name: string; type: string; fields?: unknown[] }): string {
        switch (field.type) {
          case 'text': case 'url': case 'richtext': return 'string';
          case 'number': return 'number';
          case 'boolean': return 'boolean';
          case 'media': return 'number | null';
          case 'select': return 'string';
          case 'repeater': {
            if (!field.fields || !Array.isArray(field.fields)) return 'unknown[]';
            const inner = (field.fields as { name: string; type: string }[])
              .map((f) => `    ${f.name}: ${fieldToTs(f)};`)
              .join('\n');
            return `Array<{\n${inner}\n  }>`;
          }
          default: return 'unknown';
        }
      }

      function pascalCase(slug: string): string {
        return slug.split(/[_-]/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
      }

      let output = `/**\n * Auto-generated by WollyCMS — do not edit manually.\n * Generated: ${new Date().toISOString()}\n */\n\n`;

      // Block type interfaces
      output += '// Block type field interfaces\n';
      for (const bt of btRows) {
        const fields = (bt.fieldsSchema as { name: string; type: string; required?: boolean; fields?: unknown[] }[]) || [];
        output += `export interface ${pascalCase(bt.slug)}Fields {\n`;
        for (const f of fields) {
          const optional = f.required ? '' : '?';
          output += `  ${f.name}${optional}: ${fieldToTs(f)};\n`;
        }
        output += '}\n\n';
      }

      // Content type interfaces
      output += '// Content type interfaces\n';
      for (const ct of ctRows) {
        const regions = (ct.regions as { name: string; label: string }[]) || [];
        output += `export interface ${pascalCase(ct.slug)}Page {\n`;
        output += '  id: number;\n';
        output += `  type: '${ct.slug}';\n`;
        output += '  title: string;\n';
        output += '  slug: string;\n';
        output += "  status: 'draft' | 'published' | 'archived';\n";
        output += '  fields: Record<string, unknown>;\n';
        output += '  seo?: { meta_title: string | null; meta_description: string | null; og_image: string | null; canonical_url: string | null; robots: string | null };\n';
        output += '  regions: {\n';
        for (const r of regions) {
          output += `    ${r.name}?: import('@wollycms/astro').ResolvedBlock[];\n`;
        }
        output += '  };\n';
        output += '  meta: { created_at: string; updated_at: string; published_at: string | null };\n';
        output += '}\n\n';
      }

      // Union type
      const pageUnion = ctRows.map((ct: typeof ctRows[0]) => `${pascalCase(ct.slug)}Page`).join(' | ');
      output += `export type WollyPage = ${pageUnion};\n\n`;

      // Block type slug union
      const blockSlugs = btRows.map((bt: typeof btRows[0]) => `'${bt.slug}'`).join(' | ');
      output += `export type BlockTypeSlug = ${blockSlugs};\n\n`;

      // Content type slug union
      const ctSlugs = ctRows.map((ct: typeof ctRows[0]) => `'${ct.slug}'`).join(' | ');
      output += `export type ContentTypeSlug = ${ctSlugs};\n`;

      writeFileSync(outputPath, output);
      console.log(`Types generated: ${outputPath}`);
      console.log(`  ${ctRows.length} content types, ${btRows.length} block types`);
      break;
    }

    case 'import': {
      const filePath = process.argv[3];
      if (!filePath) {
        console.error('Usage: wolly import <file.json>');
        process.exit(1);
      }
      const { readFileSync } = await import('fs');
      const { getDb } = await import('./db/index.js');
      const { eq } = await import('drizzle-orm');
      const schema = await import('./db/schema/index.js');

      let data: Record<string, unknown>;
      try {
        data = JSON.parse(readFileSync(filePath, 'utf-8'));
      } catch {
        console.error(`Failed to read or parse ${filePath}`);
        process.exit(1);
      }

      if ((data as { version?: number }).version !== 1) {
        console.error('Invalid export format (expected version: 1)');
        process.exit(1);
      }

      const db = getDb();
      const importTable = async (
        name: string,
        table: any,
        rows: unknown[],
        dedup: (row: Record<string, unknown>) => ReturnType<typeof eq>,
      ) => {
        let imported = 0;
        for (const row of rows as Record<string, unknown>[]) {
          const [existing] = await db.select().from(table).where(dedup(row)).limit(1);
          if (!existing) {
            await db.insert(table).values(row);
            imported++;
          }
        }
        console.log(`  ${name}: ${imported} new / ${rows.length} total`);
      };

      console.log('Importing...');
      const d = data as Record<string, unknown[]>;
      if (d.contentTypes?.length) await importTable('contentTypes', schema.contentTypes, d.contentTypes, (r) => eq(schema.contentTypes.slug, r.slug as string));
      if (d.blockTypes?.length) await importTable('blockTypes', schema.blockTypes, d.blockTypes, (r) => eq(schema.blockTypes.slug, r.slug as string));
      if (d.taxonomies?.length) await importTable('taxonomies', schema.taxonomies, d.taxonomies, (r) => eq(schema.taxonomies.slug, r.slug as string));
      if (d.terms?.length) await importTable('terms', schema.terms, d.terms, (r) => eq(schema.terms.slug, r.slug as string));
      if (d.pages?.length) await importTable('pages', schema.pages, d.pages, (r) => eq(schema.pages.slug, r.slug as string));
      if (d.blocks?.length) await importTable('blocks', schema.blocks, d.blocks, (r) => eq(schema.blocks.id, r.id as number));
      if (d.pageBlocks?.length) await importTable('pageBlocks', schema.pageBlocks, d.pageBlocks, (r) => eq(schema.pageBlocks.id, r.id as number));
      if (d.menus?.length) await importTable('menus', schema.menus, d.menus, (r) => eq(schema.menus.slug, r.slug as string));
      if (d.menuItems?.length) await importTable('menuItems', schema.menuItems, d.menuItems, (r) => eq(schema.menuItems.id, r.id as number));
      if (d.redirects?.length) await importTable('redirects', schema.redirects, d.redirects, (r) => eq(schema.redirects.fromPath, r.fromPath as string));
      console.log('Import complete.');
      break;
    }

    case 'og:generate': {
      const { getDb } = await import('./db/index.js');
      const { bulkGenerateOgImages } = await import('./og/generate.js');
      getDb(); // ensure DB is initialized

      const args = process.argv.slice(3);
      const force = args.includes('--force');
      const dryRun = args.includes('--dry-run');
      const typeIdx = args.indexOf('--type');
      const contentTypeSlug = typeIdx > -1 ? args[typeIdx + 1] : undefined;

      console.log(`OG Image Generation${dryRun ? ' (dry run)' : ''}`);
      console.log(`  Mode: ${force ? 'regenerate all' : 'missing only'}`);
      if (contentTypeSlug) console.log(`  Content type: ${contentTypeSlug}`);
      console.log('');

      const result = await bulkGenerateOgImages({
        force,
        dryRun,
        contentTypeSlug,
      });

      console.log('');
      console.log(`Done. Generated: ${result.generated}, Skipped: ${result.skipped}`);
      if (result.errors.length > 0) {
        console.log(`Errors: ${result.errors.length}`);
        for (const err of result.errors) console.log(`  - ${err}`);
      }
      break;
    }

    case 'health': {
      const { env } = await import('./env.js');
      const url = `http://${env.HOST === '0.0.0.0' ? 'localhost' : env.HOST}:${env.PORT}/api/health`;
      try {
        const res = await fetch(url);
        const json = await res.json();
        console.log(JSON.stringify(json, null, 2));
      } catch {
        console.error(`Could not reach server at ${url}`);
        process.exit(1);
      }
      break;
    }

    case 'search:rebuild': {
      const { getDb: getDbForSearch } = await import('./db/index.js');
      const { rebuildSearchIndex } = await import('./search-index.js');
      getDbForSearch();
      console.log('Rebuilding search index...');
      const count = await rebuildSearchIndex();
      console.log(`Indexed ${count} published pages.`);
      break;
    }

    default:
      console.log(`WollyCMS CLI v0.1.0

Usage: wolly <command>

Commands:
  migrate              Run pending database migrations
  seed                 Populate database with sample data
  start                Start the production server
  export               Export all data as JSON to stdout
  import <file>        Import data from a JSON backup file
  types generate       Generate TypeScript types from CMS schemas
  og:generate          Generate OG images for published pages
  search:rebuild       Rebuild full-text search index
  health               Check server health status

Examples:
  wolly migrate
  wolly seed
  wolly export > backup.json
  wolly import backup.json
  wolly types generate --output src/wolly-types.d.ts
  wolly og:generate                    # pages missing OG images
  wolly og:generate --force            # regenerate all
  wolly og:generate --type=blog        # specific content type
  wolly og:generate --dry-run          # preview without generating
  wolly search:rebuild                 # rebuild FTS index`);
      if (command) {
        console.error(`\nUnknown command: ${command}`);
        process.exit(1);
      }
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
